### ISSUE TITLE
aarch64 ubuntu release compile error 

### ISSUE THREAD

**Issue by luqinlive** [gozfree/gear-lib#46]
hi, I'm compile in arm box with ubuntu 16.04 , debug is ok ,but release print errors ,
==== clean linux libmacro done.
==== clean linux libtime done.
==== clean linux liblog done.
==== clean linux libgevent done.
==== clean linux libworkq done.
==== clean linux libdict done.
==== clean linux libhash done.
==== clean linux libsort done.
==== clean linux librbtree done.
==== clean linux libringbuffer done.
==== clean linux libthread done.
==== clean linux libconfig done.
==== clean linux libvector done.
==== clean linux libbase64 done.
==== clean linux libdebug done.
==== clean linux libfile done.
==== clean linux libuvc done.
==== clean linux libmp4parser done.
==== clean linux libqueue done.
==== clean linux libplugin done.
==== clean linux libhal done.
==== clean linux libsubmask done.
==== clean linux libskt done.
==== clean linux librpc done.
==== clean linux librtsp done.
==== clean linux libipc done.
==== build linux libmacro done.
libtime.c: In function ‘int time_get_info_by_utc(uint32_t, time_info*)’:
libtime.c:193:5: error: ‘%03d’ directive output may be truncated writing between 3 and 5 bytes into a region of size 4 [-Werror=format-truncation=]
 int time_get_info_by_utc(uint32_t utc, struct time_info *ti)
     ^~~~~~~~~~~~~~~~~~~~
libtime.c:193:5: note: directive argument in the range [0, 65535]
In file included from /usr/include/stdio.h:862:0,
                 from libtime.c:22:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 6 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
libtime.c: In function ‘int time_get_info_by_msec(uint64_t, time_info*)’:
libtime.c:227:5: error: ‘%03d’ directive output may be truncated writing between 3 and 5 bytes into a region of size 4 [-Werror=format-truncation=]
 int time_get_info_by_msec(uint64_t msec, struct time_info *ti)
     ^~~~~~~~~~~~~~~~~~~~~
libtime.c:227:5: note: directive argument in the range [0, 65535]
In file included from /usr/include/stdio.h:862:0,
                 from libtime.c:22:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 6 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
libtime.c: In function ‘int time_get_info(time_info*)’:
libtime.c:267:5: error: ‘%03d’ directive output may be truncated writing between 3 and 5 bytes into a region of size 4 [-Werror=format-truncation=]
 int time_get_info(struct time_info *ti)
     ^~~~~~~~~~~~~
libtime.c:267:5: note: directive argument in the range [0, 65535]
In file included from /usr/include/stdio.h:862:0,
                 from libtime.c:22:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 6 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
cc1plus: all warnings being treated as errors
make: *** [libtime.o] Error 1

**Comment by gozfree** [comment]
[already fix it](https://github.com/gozfree/gear-lib/commit/3d15be8ecd16fa31fc6afa3019de6642fa55a5b7)

**Comment by luqinlive** [comment]
hisi  cross platform compile error ,  
modify build.sh  pi config to CROSS_PREFIX=aarch64-himix100-linux-  
use  ./build.sh all  pi release 
and i got this error :
==== build pi libhal done.
==== build pi libsubmask done.
==== build pi libskt done.
gcc: error: missing argument to ‘-L’
make: *** [test_librpc] Error 1

thansk.
